import { pretendardFont } from "@/style/fonts/font-pretendard";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={`${pretendardFont.variable}`}>
      <body>{children}</body>
    </html>
  );
}
