import { pretendardFont } from "@/style/fonts/font-pretendard";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={`${pretendardFont.variable}`}>
      <body>
        <Header />
        <main className="h-[300vh]">{children}</main>
      </body>
    </html>
  );
}
